### ISSUE TITLE
I wish to see your pic 

### ISSUE THREAD

**Issue by AraafRoyall** [canyie/canyie#1]
😂😂.

I am from India .
i want to see your pic.
You can contact me on Telegram @AraafRoyall 🙂🙂

**Comment by canyie** [comment]
I'm from another nation, imagination, so here it is 
![](https://canyie.github.io/data/image/avatar_new.jpg)

**Comment by AraafRoyall** [comment]
i want to see your real photo , 
Can you show me yourself , either here or Telegram..

i know imagination too well , But i want to real 🙂🙂

**Comment by AraafRoyall** [comment]
as you wrote 19 Yr old. similar to my age , so i want to see you 🙂🙂

**Comment by AraafRoyall** [comment]
> I'm from another nation, imagination, so here it is 
> ![](https://canyie.github.io/data/image/avatar_new.jpg)

Hi see your name in Magisk App 🙂..

Will you reply or i should close this issue
